version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
volumes:
  postgres_volume:
